# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyAssetBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyAssetBook

  target 'MyAssetBookTests' do
    # Pods for testing
  end

end
