# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Students-platform-app-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Students-platform-app-ios

  target 'Students-platform-app-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Students-platform-app-iosUITests' do
    # Pods for testing
  end

end
